### ISSUE TITLE
Error CFBundleShortVersionString

### ISSUE THREAD

**Issue by marcotammaro** [Swiftgram/TDLibFramework#258]
Hello, when I try to upload an app using TDLibFramework to TestFlight (Xcode -> Product -> Archive -> Upload) I got an error from App Store Analysis related to an incompatible format of CFBundleShortVersionString.

The complete error is:

```
Asset validation failed
This bundle is invalid. The value for key CFBundleShortVersionString *1.8.28-2424d681' in the
Info.plist file at "Payload/AppName.app/Frameworks/
TDLibFramework.framework' must be a period-separated list of at most three non-negative
integers. Please find more information about CFBundleShortVersionString at https://
developer.apple.com/documentation/bundleresources/information_property_list/
cfbundleshortversionstring
```

Any idea on how it can be solved?

**Comment by Kylmakalle** [comment]
Fixed in https://github.com/Swiftgram/TDLibFramework/commit/f338178de8d9d453aa5b4d84d3ecae87a7b40050
CI will publish a release soon. If you're using [TDLibKit](github.com/Swiftgram/TDLibKit), the Kit will pick up the changes later this day.

**Comment by Kylmakalle** [comment]
Fixed in https://github.com/Swiftgram/TDLibFramework/releases/tag/1.8.29-39d82693

**Comment by marcotammaro** [comment]
@Kylmakalle Thank you so much 😁
