### ISSUE TITLE
SPM Can't download it?

### ISSUE THREAD

**Issue by LvBing1990** [Swiftgram/TDLibFramework#81]
![image](https://user-images.githubusercontent.com/100563041/156279743-dee2e47a-a7b4-4197-8f08-9387aab63a53.png)
Can you get this approved by Apple? I'm using is libtdjson.dylib,But Apple turned it down，Because contain .dylib. So I'm looking for another way，I wonder if you can help me.
<img width="586" alt="WeChat185f2cfc95406d3837a6effd27df3f27" src="https://user-images.githubusercontent.com/100563041/156281419-1ace9d85-2e0e-4873-b07e-a98f73504789.png">
Is there a problem with the network?

**Comment by Kylmakalle** [comment]
Definitely a network error
